services:
  db-dev:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: dev
    volumes:
      - pgdata-dev:/var/lib/postgresql
  db-test:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: test
    volumes:
      - pgdata-test:/var/lib/postgresql
volumes:
  pgdata-dev:
  pgdata-test:
